site_name: 我的个人笔记库

theme:
  name: material
  language: zh
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: 切换至深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 切换至浅色模式
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top            # 回到顶部按钮
    - content.code.copy         # 代码块一键复制按钮
    - content.code.annotate     # 代码注释增强
    - search.suggest            # 搜索建议

plugins:
  - search:
      lang: [en, ja]
  - awesome-pages               # 关键插件：自动识别目录结构

markdown_extensions:
  - pymdownx.inlinehilite          # 支持行内代码高亮
  - pymdownx.snippets
  - pymdownx.superfences:          # 支持标准的代码块围栏
      preserve_tabs: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true   # 【关键】这一行负责把颜色类注入到 HTML 中
  - extra

# 更换为安全的 CDN 链接
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js